name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.4.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f31c0cdc8b2ff74ee3a2e62eb80015867c72a7d88d7bbea25a36a02fea14a9c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.203"
