name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.2.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ce468436944787311c5546514e63f33bcd6eca68e2f3ddc154bb0f22d735d8a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
