name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.4.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92743548c3e8b13a93ff50f9188a9d770c33d15fb1eba9518abf1ee97bd284c8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.205"
