name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.4.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e6fa4eda24b75595dfef9f131824acba1919988d1094d7b87eb3ce795feb8bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.205"
