name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.2.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67b77fdb4957d4ae306603ee4f400a184ba2bb03f8d56077d0b6f54740a5df14"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.196"
