name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.2.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24c1be0e7f4d6eb7e1fc00bba2300104ea00324023504251bcdba9d3e0ce3297"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
