name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.1.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b62b36b7cd1f35dcf8e2cc99373044d7f471401d0cce9d0ac9847e805976f7d1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
