name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.3.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0639617da77333063a0e1c8477deee9dc4040d4706c5ae7c4a933f021359f58f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.196"
