name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.4.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f7ba4713ac883ab37e57a81216e5885fffa628f2c2f36f2f9c4145d448d0919"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.203"
