name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.2.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c590027076a625037ab6576fbcda0be7ba01352057ac15cbf15c34afabf881b8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
