name = "CreateD"
author = "Diamond Drake Ventures"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd372a4bc527bad466325475254c191f6e7ecb804a456eb8576dc8a244e53a11"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
