name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.2.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe66329a2b8b857911374ff8a237c8d74ec902ebeec09026da41b6ec9ccb6621"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
