name = "CreateD"
author = "Diamond Drake Ventures"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2e5af174d19f53c06fdadd712b27e7993beb3096b77e1961e12178ecfb7d0e6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
