name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.3.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a08bd33e62f1c45759dd817107a2eb9cf3a743f6d4a1524e1a6ac9053f89697a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.196"
