name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.3.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dda7e6f549c20b9a553163f4978781325c5cc32cf3f650523ca9c83afdbb5ea2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.196"
