name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.4.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "719f5b52f3600cda47d3d85d7c712f02117e0cc62fcd03e2742b530cc450f897"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.203"
