name = "CreateD"
author = "Diamond Drake Ventures"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a875713ea7278cd21b0661c21eeab05e411f31fa23840448df1727e59478b80"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
