name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.4.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a6fd19c12ec8e41eb0941f6ec93d174a1c5118542e2c731bd97a68475982f7a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.205"
