name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.1.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebba041024bfba9d60b4f6b97f66b2f55d9aa4207dcbf6453ef241fbeee285fe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
