name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.1.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c307f02b8c5cf9e21bfbd95a32e9121b5cea0cba6315117c6674a204641c8bdc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
