name = "Create(D)"
author = "Diamond Drake Ventures"
version = "0.2.0"
description = "Create+ modpack that sticks to the Vanilla+ experience"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42f0b87a65cf20436fa8d1a274b97b2f94ae4388293fd4431e742c87301791ab"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
