name = "CreateD"
author = "Diamond Drake Ventures"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f44dd5d4860a3f6008c6cb81ff3360df00f475a60210a27e48dae29d0dc29a65"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
